import datetime
import requests
import json
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, Border, Side, Alignment

# --- CONFIGURATION ---
EXCEL_FILE_PATH = "my_record_book.xlsx"

# --- OLLAMA LLM CONFIGURATION ---
# This should be the model you downloaded with 'ollama run'
OLLAMA_MODEL = "gemma3:1b"
OLLAMA_HOST = "http://localhost:11434"


def generate_summary_with_ollama(tasks_for_week, model=OLLAMA_MODEL, host=OLLAMA_HOST):
    """
    Sends weekly tasks to a local LLM via Ollama to generate a summary of
    potential problems and solutions.

    Args:
        tasks_for_week (str): A single string containing all tasks for the week.
        model (str): The name of the Ollama model to use.
        host (str): The URL of the Ollama API endpoint.

    Returns:
        tuple: A tuple containing (problems_encountered, solutions_found).
               Returns a default message if the API call fails.
    """
    if not tasks_for_week.strip():
        return "No specific problems noted.", "Solutions were implemented as part of the tasks."

    # This prompt is engineered to ask the LLM for a JSON response, which is more reliable to parse.
    prompt = f"""
    Based on the following list of tasks completed in a week, act as a project manager's assistant 
    to infer one potential problem or challenge that might have been encountered and one corresponding 
    solution that was likely found.

    Your response MUST be a single, valid JSON object with two keys: "problems_encountered" and "solutions_found".
    Do not add any text before or after the JSON object.

    Example Response Format:
    {{
        "problems_encountered": "The initial data preprocessing was time-consuming due to inconsistent data formats from the source.",
        "solutions_found": "A reusable data cleaning script was developed to automate the preprocessing and ensure consistency for future tasks."
    }}

    Here are the tasks for the week:
    ---
    {tasks_for_week}
    ---
    """

    try:
        payload = {
            "model": model,
            "prompt": prompt,
            "format": "json",  # Request JSON output from the model
            "stream": False  # Get the full response at once
        }

        response = requests.post(f"{host}/api/generate", json=payload, timeout=120)
        response.raise_for_status()

        # The response from Ollama is a JSON string, we need to parse it to get the 'response' field
        response_data = json.loads(response.text)

        # The actual content generated by the model is in the 'response' key
        llm_output = json.loads(response_data.get('response', '{}'))

        problems = llm_output.get("problems_encountered", "Could not generate summary.")
        solutions = llm_output.get("solutions_found", "Could not generate summary.")

        return problems, solutions

    except requests.exceptions.RequestException as e:
        print(f"Error connecting to Ollama: {e}")
        return "Ollama server not reachable.", "Please ensure Ollama is running."
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON from LLM response: {e}")
        return "Invalid response from LLM.", "Could not parse the summary."


def create_table_structure(ws, start_row):
    """Creates the static structure for a single weekly table."""
    bold_font = Font(bold=True)
    center_align = Alignment(horizontal='center', vertical='center', wrap_text=True)
    left_align = Alignment(horizontal='left', vertical='center')
    thin_side = Side(border_style="thin", color="000000")
    thin_border = Border(left=thin_side, right=thin_side, top=thin_side, bottom=thin_side)
    headers = {'A': "DAYS", 'B': "DATE", 'C': "DESCRIPTION OF WORK CARRIED OUT", 'D': "ACTIVITY NO."}
    ws[f'A{start_row}'] = "WEEK ENDING"
    ws[f'A{start_row}'].font = bold_font
    header_row = start_row + 1
    for col_letter, header_text in headers.items():
        cell = ws[f'{col_letter}{header_row}']
        cell.value = header_text
        cell.font = bold_font
        cell.alignment = center_align
    days_of_week = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]
    for i, day in enumerate(days_of_week):
        ws[f'A{start_row + 2 + i}'].value = day
    ws[f'C{start_row + 9}'].value = "PROBLEMS ENCOUNTERED"
    ws[f'C{start_row + 9}'].font = bold_font
    ws[f'D{start_row + 9}'].value = "SOLUTIONS FOUND"
    ws[f'D{start_row + 9}'].font = bold_font
    ws.merge_cells(f'A{start_row + 11}:D{start_row + 11}')
    ws[f'A{start_row + 11}'].value = "INDUSTRIAL SUPERVISOR'S COMMENTS"
    ws[f'A{start_row + 11}'].font = bold_font
    ws.merge_cells(f'A{start_row + 12}:D{start_row + 12}')
    ws.merge_cells(f'A{start_row + 13}:B{start_row + 13}')
    ws[f'A{start_row + 13}'].value = "DESIGNATION"
    ws[f'A{start_row + 13}'].font = bold_font
    ws.merge_cells(f'C{start_row + 13}:D{start_row + 13}')
    for row in ws.iter_rows(min_row=start_row, max_row=start_row + 13, min_col=1, max_col=4):
        for cell in row:
            cell.border = thin_border


def read_tasks_from_sheet(wb, task_sheet_name):
    """Reads tasks from a sheet and maps them to dates."""
    tasks = {}
    if task_sheet_name in wb.sheetnames:
        ws_tasks = wb[task_sheet_name]
        for row in ws_tasks.iter_rows(min_row=2, values_only=True):
            date_val, task_description = row[0], row[1]
            if date_val and task_description:
                task_date = date_val.date() if isinstance(date_val, datetime.datetime) else None
                if task_date:
                    tasks[task_date] = str(task_description).strip()
    else:
        print(f"Warning: Task sheet '{task_sheet_name}' not found.")
    return tasks


def generate_weekly_report(start_date_str, end_date_str, sheet_name, task_sheet_name):
    """Main function to generate the report and fill summaries with LLM."""
    tasks_data = {}
    try:
        start_date = datetime.datetime.strptime(start_date_str, "%Y-%m-%d").date()
        end_date = datetime.datetime.strptime(end_date_str, "%Y-%m-%d").date()
    except ValueError:
        print("Error: Please use the YYYY-MM-DD format for dates.")
        return

    try:
        wb = load_workbook(EXCEL_FILE_PATH)
        tasks_data = read_tasks_from_sheet(wb, task_sheet_name)
        ws = wb[sheet_name] if sheet_name in wb.sheetnames else wb.create_sheet(title=sheet_name)
    except FileNotFoundError:
        wb = Workbook()
        ws = wb.active
        ws.title = sheet_name
        ws.column_dimensions['A'].width = 18
        ws.column_dimensions['B'].width = 15
        ws.column_dimensions['C'].width = 45
        ws.column_dimensions['D'].width = 20
        print(f"Info: '{EXCEL_FILE_PATH}' not found. A new file will be created.")

    row_offset = ws.max_row + 3 if ws.max_row > 1 else 1
    current_date = start_date
    is_new_week = True
    weekly_tasks_summary = ""

    while current_date <= end_date:
        if is_new_week:
            create_table_structure(ws, row_offset)
            is_new_week = False

        day_index = current_date.weekday()
        current_data_row = row_offset + 2 + day_index

        ws[f'B{current_data_row}'].value = current_date.strftime("%Y-%m-%d")

        if current_date in tasks_data:
            task_description = tasks_data[current_date]
            ws[f'C{current_data_row}'].value = task_description
            ws[f'C{current_data_row}'].alignment = Alignment(wrap_text=True)
            weekly_tasks_summary += f"- {task_description}\n"

        # When the week ends (Sunday) or it's the last day of the range
        if day_index == 6 or current_date == end_date:
            ws[f'B{row_offset}'].value = current_date.strftime("%Y-%m-%d")
            ws[f'B{row_offset}'].font = Font(bold=True)

            print(f"\nGenerating summary for week ending {current_date}...")
            problems, solutions = generate_summary_with_ollama(weekly_tasks_summary)

            ws[f'C{row_offset + 10}'].value = problems
            ws[f'D{row_offset + 10}'].value = solutions

            # Reset for the next week
            row_offset += 16
            is_new_week = True
            weekly_tasks_summary = ""

        current_date += datetime.timedelta(days=1)

    wb.save(EXCEL_FILE_PATH)
    print(f"\nSuccessfully updated report: {EXCEL_FILE_PATH} (Sheet: {sheet_name})")


if __name__ == "__main__":
    START_DATE = "2025-05-15"
    END_DATE = "2025-09-30"
    SHEET_NAME = "log1"
    TASK_SHEET_NAME = "task_sheet"

    generate_weekly_report(START_DATE, END_DATE, SHEET_NAME, TASK_SHEET_NAME)